name: Ürün Verileri Kontrolü

on:
  pull_request:
    branches: [ "main", "master" ]

jobs:
  python-check:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları GitHub'dan Çek
        uses: actions/checkout@v6

      - name: Python Ortamını Hazırla
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Sadece urun_verileri.py Dosyasını Test Et
        run: |
          echo ">>> urun_verileri.py dosyasında syntax hatası var mı bakılıyor..."
          python -m py_compile python/urun_verileri.py
          
          echo ">>> Dosya başarıyla derlendi, hiçbir yazım hatası yok! ✅"